groups:
  - name: admins
    members:
      - "0x36615Cf349d7F6344891B1e7CA7C72883F5dc049" # Default Rich account
contracts:
  # USDG
  - address: "0x49F4849e730Ea4AfE26b43693b9F1b81c21b1b02"
    methods:
      - signature: function decimals() public view virtual returns (uint8)
        read:
          type: public
        write:
          type: public
      - signature: function mint(address _to, uint256 _amount) public returns (bool)
        read:
          type: public
        write:
          type: public
      - signature: function symbol() public view virtual returns (string memory)
        read:
          type: public
        write:
          type: public
      - signature: totalSupply()
        read:
          type: public
        write:
          type: public
      - signature: "function balanceOf(address) view returns (uint256)"
        read:
          type: checkArgument
          argIndex: 0
        write:
          type: closed
      - signature: "function allowance(address, address) view returns (uint256)"
        read:
          type: oneOf
          rules:
            - type: checkArgument
              argIndex: 0
            - type: checkArgument
              argIndex: 1
        write:
          type: closed
      - signature: function approve(address spender, uint256 value) public returns (bool)
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function transferFrom(address from, address to, uint256 value) public virtual returns (bool)
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function increaseAllowance(address spender, uint256 addedValue) returns bool
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function decreaseAllowance(address spender, uint256 addedValue) returns bool
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: authorizedBalanceOf(address)(uint256)
        read:
          type: public
        write:
          type: public
      - signature: function puclicThreshold(address target) public view returns (uint256, bool)
        read:
          type: public
        write:
          type: closed
      - signature: function changePublicThreshold(uint256 publicThreshold) external
        read:
          type: public
        write:
          type: public
      - signature: function supportsInterface(bytes4) view
        read:
          type: public
        write:
          type: public
  # wAAPL
  - address: "0xcB4305db20D1ABB16cb531AaD36dAE4A133FA601"
    methods:
      - signature: function decimals() public view virtual returns (uint8)
        read:
          type: public
        write:
          type: public
      - signature: function mint(address _to, uint256 _amount) public returns (bool)
        read:
          type: public
        write:
          type: public
      - signature: function symbol() public view virtual returns (string memory)
        read:
          type: public
        write:
          type: public
      - signature: totalSupply()
        read:
          type: public
        write:
          type: public
      - signature: "function balanceOf(address) view returns (uint256)"
        read:
          type: checkArgument
          argIndex: 0
        write:
          type: closed
      - signature: "function allowance(address, address) view returns (uint256)"
        read:
          type: oneOf
          rules:
            - type: checkArgument
              argIndex: 0
            - type: checkArgument
              argIndex: 1
        write:
          type: closed
      - signature: function approve(address spender, uint256 value) public returns (bool)
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function transferFrom(address from, address to, uint256 value) public virtual returns (bool)
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function increaseAllowance(address spender, uint256 addedValue) returns bool
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function decreaseAllowance(address spender, uint256 addedValue) returns bool
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: authorizedBalanceOf(address)(uint256)
        read:
          type: public
        write:
          type: public
      - signature: function puclicThreshold(address target) public view returns (uint256, bool)
        read:
          type: public
        write:
          type: closed
      - signature: function changePublicThreshold(uint256 publicThreshold) external
        read:
          type: public
        write:
          type: public
      - signature: function supportsInterface(bytes4) view
        read:
          type: public
        write:
          type: public
  # L2_INTEROP_HANDLER
  - address: "0x000000000000000000000000000000000001000b"
    methods:
      - signature: function getAliasedAccount(address fromAsSalt, uint256) view returns (address)
        read:
          type: public
        write:
          type: closed
  # L2_INTEROP_CENTER_ADDRESS
  - address: "0x000000000000000000000000000000000001000a"
    methods:
      - signature: function requestInterop(uint256 _destinationChainId, address _executionAddress, tuple[] _feePaymentCallStarters, tuple[] _executionCallStarters, tuple _gasFields) payable returns (bytes32 canonicalTxHash)
        read:
          type: public
        write:
          type: public