groups:
  - name: admins
    members:
      - "0x36615Cf349d7F6344891B1e7CA7C72883F5dc049" # Default Rich account
contracts:
  # CPAMM
  - address: "0x9201F71D61F799449d2a5C85aa3498307371b5fE"
    methods:
      - signature: function getReserves() external view returns (uint256, uint256)
        read:
          type: public
        write:
          type: closed
      - signature: function swap(address _tokenIn, uint256 _amountIn) external returns (uint256)
        read:
          type: public
        write:
          type: public
      - signature: function allowedToAddLiquidity()
        read:
          type: public
        write:
          type: public
      - signature: function addLiquidity(uint256 _amount0, uint256 _amount1) external returns (uint256 shares)
        read:
          type: public
        write:
          type: public
      - signature: function removeLiquidity(uint256 _shares) external returns (uint256 amount0, uint256 amount1)
        read:
          type: public
        write:
          type: public
      - signature: function getUserFee(address user) returns (uint256)
        read:
          type: public
        write:
          type: public
      - signature: function getRemainingDailyAllowance(address) returns (uint256)
        read:
          type: public
        write:
          type: public
      - signature: function balanceOf(address) returns (uint256)
        read:
          type: public
        write:
          type: closed
  # TradeEscrow.sol
  - address: "0x1f8739025D7f95D026688cfBB70579e00bC33148"
    methods:
      - signature: function acceptTrade(uint256)
        read:
          type: public
        write:
          type: public
      - signature: function cancelTrade(uint256)
        read:
          type: public
        write:
          type: public
      - signature: function deposit(uint256)
        read:
          type: public
        write:
          type: public
      - signature: function getMySwaps(address)
        read:
          type: checkArgument
          argIndex: 0
        write:
          type: public
      - signature: function proposeTrade(address,uint256,address,uint256,address,uint256)
        read:
          type: public
        write:
          type: public
      - signature: function tradeCounter()
        read:
          type: closed
        write:
          type: closed
      - signature: function trades(uint256)
        read:
          type: closed
        write:
          type: closed
      - signature: function userTrades(address,uint256)
        read:
          type: closed
        write:
          type: closed
  # USDG
  - address: "0xf290e056d3C49e026fEfe41eA4017CF6d22e57bd"
    methods:
      - signature: function decimals() public view virtual returns (uint8)
        read:
          type: public
        write:
          type: public
      - signature: function mint(address _to, uint256 _amount) public returns (bool)
        read:
          type: public
        write:
          type: public
      - signature: function symbol() public view virtual returns (string memory)
        read:
          type: public
        write:
          type: public
      - signature: totalSupply()
        read:
          type: public
        write:
          type: public
      - signature: "function balanceOf(address) view returns (uint256)"
        read:
          type: checkArgument
          argIndex: 0
        write:
          type: closed
      - signature: "function allowance(address, address) view returns (uint256)"
        read:
          type: oneOf
          rules:
            - type: checkArgument
              argIndex: 0
            - type: checkArgument
              argIndex: 1
        write:
          type: closed
      - signature: function approve(address spender, uint256 value) public returns (bool)
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function transferFrom(address from, address to, uint256 value) public virtual returns (bool)
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function increaseAllowance(address spender, uint256 addedValue) returns bool
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function decreaseAllowance(address spender, uint256 addedValue) returns bool
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: authorizedBalanceOf(address)(uint256)
        read:
          type: public
        write:
          type: public
      - signature: function puclicThreshold(address target) public view returns (uint256, bool)
        read:
          type: public
        write:
          type: closed
      - signature: function changePublicThreshold(uint256 publicThreshold) external
        read:
          type: public
        write:
          type: public
      - signature: function supportsInterface(bytes4) view
        read:
          type: public
        write:
          type: public
  # wAAPL
  - address: "0x469696e7b648254451771C28A51f5Ed8e3301a9e"
    methods:
      - signature: function decimals() public view virtual returns (uint8)
        read:
          type: public
        write:
          type: public
      - signature: function mint(address _to, uint256 _amount) public returns (bool)
        read:
          type: public
        write:
          type: public
      - signature: function symbol() public view virtual returns (string memory)
        read:
          type: public
        write:
          type: public
      - signature: totalSupply()
        read:
          type: public
        write:
          type: public
      - signature: "function balanceOf(address) view returns (uint256)"
        read:
          type: checkArgument
          argIndex: 0
        write:
          type: closed
      - signature: "function allowance(address, address) view returns (uint256)"
        read:
          type: oneOf
          rules:
            - type: checkArgument
              argIndex: 0
            - type: checkArgument
              argIndex: 1
        write:
          type: closed
      - signature: function approve(address spender, uint256 value) public returns (bool)
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function transferFrom(address from, address to, uint256 value) public virtual returns (bool)
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function increaseAllowance(address spender, uint256 addedValue) returns bool
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: function decreaseAllowance(address spender, uint256 addedValue) returns bool
        # This doesn't leek information because we validate that current user
        # is msg.sender.
        read:
          type: public
        write:
          type: public
      - signature: authorizedBalanceOf(address)(uint256)
        read:
          type: public
        write:
          type: public
      - signature: function puclicThreshold(address target) public view returns (uint256, bool)
        read:
          type: public
        write:
          type: closed
      - signature: function changePublicThreshold(uint256 publicThreshold) external
        read:
          type: public
        write:
          type: public
      - signature: function supportsInterface(bytes4) view
        read:
          type: public
        write:
          type: public
  # L2_INTEROP_HANDLER
  - address: "0x000000000000000000000000000000000001000b"
    methods:
      - signature: function getAliasedAccount(address fromAsSalt, uint256) view returns (address)
        read:
          type: public
        write:
          type: closed
  # L2_INTEROP_CENTER_ADDRESS
  - address: "0x000000000000000000000000000000000001000a"
    methods:
      - signature: function requestInterop(uint256 _destinationChainId, address _executionAddress, tuple[] _feePaymentCallStarters, tuple[] _executionCallStarters, tuple _gasFields) payable returns (bytes32 canonicalTxHash)
        read:
          type: public
        write:
          type: public